# Generated by Django 5.2.6 on 2025-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(max_length=14)),
                ("dia_pagamento", models.PositiveSmallIntegerField()),
                ("valor_sessao", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "saldo_devedor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="pacientes/"),
                ),
            ],
        ),
    ]
